fr.FileAssoc=Associations de fichiers:
fr.DescContext=Ajouter "InnoUnpacker" au menu contextuel des fichiers exe
fr.InnoUnpack=Ouvrez le fichier de &Inno Setup Installer avec InnoUnpacker

de.FileAssoc=Dateizuordnungen:
de.DescContext=Füge "InnoUnpacker" zum Kontext-Menü für exe-Dateien hinzu
de.InnoUnpack=Öffne &Inno-Setup-Installer-Datei mit InnoUnpacker

it.FileAssoc=Associazione file:
it.DescContext=Aggiungi "InnoUnpacker" al menu contestuale dei file exe
it.InnoUnpack=Apri il file &Inno Setup Installer con InnoUnpacker
it.NameAndVersion={#ProgramName} {#ApplicationVersion}
it.LaunchProgram=Esegui {#ProgramName}
it.AdditionalIcons=Collegamenti:
it.CreateDesktopIcon=Crea collegamento programma sul &desktop
it.CreateQuickLaunchIcon=Crea collegamento programma nella &barra 'Avvio veloce'
it.AssocFileExtension=&Associa i file con estensione '%2' a '%1'
it.AssocingFileExtension=Associazione file con estensione '%2' a '%1'..

es.FileAssoc=Asociaciones de fichero:
es.DescContext=Añadir "InnoUnpacker" al menú contextual de ficheros exe
es.InnoUnpack=Abre el archivo &Inno Setup Installer con InnoUnpacker

zh.FileAssoc=文件关联:
zh.DescContext=将 "InnoUnpacker" ”添加到exe文件的右键菜单中
zh.InnoUnpack=使用InnoUnpacker打开Inno Setup安装程序
